{
 "title": "Builds",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_NAME", "query": "${VAR_DB_NAME}" },
   {
    "name": "arch_search",
    "label": "arch",
    "query": "SELECT architecture FROM ${DB_NAME}.builds"
   },
   {
    "name": "origin_search",
    "label": "origin",
    "query": "SELECT origin FROM ${DB_NAME}.builds"
   },
   {
    "name": "rev_search",
    "label": "rev",
    "query": "SELECT DISTINCT revision_origin_id FROM ${DB_NAME}.builds WHERE architecture LIKE ${arch_search} AND origin_id LIKE ${origin_search} AND UNIX_MILLIS(start_time) BETWEEN ${__from} AND ${__to}"
   }
  ]
 },
 "panels": [
  {
   "title": "Builds",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT COUNT (revision_origin_id) \nFROM `${DB_NAME}.builds` \nWHERE architecture LIKE ${arch_search} AND origin LIKE ${origin_search} AND revision_origin_id LIKE ${rev_search} AND UNIX_MILLIS(start_time) BETWEEN ${__from} AND ${__to}\n"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT COUNT (revision_origin_id) / \n  (SELECT COUNT (revision_origin_id) \n  FROM `${DB_NAME}.builds` \n  WHERE architecture LIKE ${arch_search} AND origin LIKE ${origin_search} AND UNIX_MILLIS(start_time) BETWEEN ${__from} AND ${__to} ) \nFROM `${DB_NAME}.builds` \nWHERE valid=true AND architecture LIKE ${arch_search} AND origin LIKE ${origin_search} AND revision_origin_id LIKE ${rev_search} AND UNIX_MILLIS(start_time) BETWEEN ${__from} AND ${__to}\n"
    }
   ]
  },
  {
   "title": "Builds per arch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "#standardSQL\r\nSELECT\r\n TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`start_time`), 10800) * 10800),\r\n  CAST (`architecture`AS String ) AS metric,\r\n  count(`architecture`) AS architecture\r\nFROM `${DB_NAME}.builds`\r\nWHERE\r\n  UNIX_MILLIS(`start_time`) BETWEEN ${__from} AND ${__to}\r\nAND origin LIKE ${origin_search}\r\nAND revision_origin_id LIKE ${rev_search}\r\nGROUP BY 1,2\r\nORDER BY 1,2 LIMIT 797"
    }
   ]
  },
  {
   "title": "Builds per revisions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "#standardSQL\r\nSELECT\r\n TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`start_time`), 10800) * 10800),\r\n  CAST (`revision_origin_id`AS String ) AS metric,\r\n  count(`revision_origin_id`) AS architecture\r\nFROM `${DB_NAME}.builds`\r\nWHERE architecture LIKE ${arch_search} AND UNIX_MILLIS(`start_time`) BETWEEN ${__from} AND ${__to}\r\nAND origin LIKE ${origin_search}\r\nGROUP BY 1,2\r\nORDER BY 1,2 LIMIT 797"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "location": "US",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT revision_origin_id, origin, architecture, MAX(start_time), COUNT(valid), COUNT(CASE WHEN valid THEN 1 END), COUNT(CASE WHEN NOT valid THEN 1 END), ARRAY_AGG(origin_id LIMIT 150)[OFFSET(0)]  \nFROM `${DB_NAME}.builds` \nWHERE architecture LIKE ${arch_search} AND origin LIKE ${origin_search} AND revision_origin_id LIKE ${rev_search} AND UNIX_MILLIS(start_time) BETWEEN ${__from} AND ${__to}\nGROUP BY revision_origin_id, architecture, origin "
    }
   ]
  }
 ]
}